### ISSUE TITLE
to_prepare is deprecated and will be removed from Rails 5.1

### ISSUE THREAD

**Issue by algodave** [ifad/eaco#7]
`DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead) (called from block in <class:Railtie> at /Users/algodave/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/eaco-b7317e1148f5/lib/eaco/railtie.rb:25)`

**Comment by safeforge** [comment]
@vjt is it possible to bump to version 1.1.1?

**Comment by vjt** [comment]
@safeforge yes please go ahead.

**Comment by safeforge** [comment]
done in d90499d
